"""Add sync_cache table

Revision ID: e238ef0d8583
Revises: 9dd00f102f7e
Create Date: 2026-01-24 23:29:43.221001+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e238ef0d8583"
down_revision: str | None = "9dd00f102f7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Apply the migration.

    This function contains the operations to upgrade the database schema
    to this revision. Operations should be idempotent where possible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_cache",
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source",
            "resource_type",
            "resource_id",
            name="uq_sync_cache_source_type_id",
        ),
    )
    with op.batch_alter_table("sync_cache", schema=None) as batch_op:
        batch_op.create_index("ix_sync_cache_fetched_at", ["fetched_at"], unique=False)
        batch_op.create_index("ix_sync_cache_source", ["source"], unique=False)
        batch_op.create_index(
            "ix_sync_cache_source_type", ["source", "resource_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration.

    This function contains the operations to downgrade the database schema
    from this revision. It should exactly reverse the upgrade operations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_cache", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_cache_source_type")
        batch_op.drop_index("ix_sync_cache_source")
        batch_op.drop_index("ix_sync_cache_fetched_at")

    op.drop_table("sync_cache")
    # ### end Alembic commands ###
