"""Add PlayerSeasonStats and SyncLog models

Revision ID: 9dd00f102f7e
Revises: 2e7d4ed5ee4f
Create Date: 2026-01-24 23:39:20.096805+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dd00f102f7e"
down_revision: str | None = "2e7d4ed5ee4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Apply the migration.

    This function contains the operations to upgrade the database schema
    to this revision. Operations should be idempotent where possible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_season_stats",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("games_started", sa.Integer(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("total_field_goals_made", sa.Integer(), nullable=False),
        sa.Column("total_field_goals_attempted", sa.Integer(), nullable=False),
        sa.Column("total_two_pointers_made", sa.Integer(), nullable=False),
        sa.Column("total_two_pointers_attempted", sa.Integer(), nullable=False),
        sa.Column("total_three_pointers_made", sa.Integer(), nullable=False),
        sa.Column("total_three_pointers_attempted", sa.Integer(), nullable=False),
        sa.Column("total_free_throws_made", sa.Integer(), nullable=False),
        sa.Column("total_free_throws_attempted", sa.Integer(), nullable=False),
        sa.Column("total_offensive_rebounds", sa.Integer(), nullable=False),
        sa.Column("total_defensive_rebounds", sa.Integer(), nullable=False),
        sa.Column("total_rebounds", sa.Integer(), nullable=False),
        sa.Column("total_assists", sa.Integer(), nullable=False),
        sa.Column("total_turnovers", sa.Integer(), nullable=False),
        sa.Column("total_steals", sa.Integer(), nullable=False),
        sa.Column("total_blocks", sa.Integer(), nullable=False),
        sa.Column("total_personal_fouls", sa.Integer(), nullable=False),
        sa.Column("total_plus_minus", sa.Integer(), nullable=False),
        sa.Column("avg_minutes", sa.Float(), nullable=False),
        sa.Column("avg_points", sa.Float(), nullable=False),
        sa.Column("avg_rebounds", sa.Float(), nullable=False),
        sa.Column("avg_assists", sa.Float(), nullable=False),
        sa.Column("avg_turnovers", sa.Float(), nullable=False),
        sa.Column("avg_steals", sa.Float(), nullable=False),
        sa.Column("avg_blocks", sa.Float(), nullable=False),
        sa.Column("field_goal_pct", sa.Float(), nullable=True),
        sa.Column("two_point_pct", sa.Float(), nullable=True),
        sa.Column("three_point_pct", sa.Float(), nullable=True),
        sa.Column("free_throw_pct", sa.Float(), nullable=True),
        sa.Column("true_shooting_pct", sa.Float(), nullable=True),
        sa.Column("effective_field_goal_pct", sa.Float(), nullable=True),
        sa.Column("assist_turnover_ratio", sa.Float(), nullable=True),
        sa.Column(
            "last_calculated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_id", "team_id", "season_id", name="uq_player_team_season_stats"
        ),
    )
    op.create_table(
        "sync_logs",
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("season_id", sa.Uuid(), nullable=True),
        sa.Column("game_id", sa.Uuid(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_created", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sync_logs_source_entity_started",
            ["source", "entity_type", "started_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration.

    This function contains the operations to downgrade the database schema
    from this revision. It should exactly reverse the upgrade operations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_sync_logs_source_entity_started")

    op.drop_table("sync_logs")
    op.drop_table("player_season_stats")
    # ### end Alembic commands ###
