"""Add game data models

Revision ID: 2e7d4ed5ee4f
Revises: 787bfece0c59
Create Date: 2026-01-24 14:40:52.162737+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e7d4ed5ee4f"
down_revision: str | None = "787bfece0c59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """
    Apply the migration.

    This function contains the operations to upgrade the database schema
    to this revision. Operations should be idempotent where possible.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('ix_games_game_date', ['game_date'], unique=False)

    op.create_table('play_by_play_events',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('event_number', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('clock', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_subtype', sa.String(length=50), nullable=True),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'event_number', name='uq_game_event_number')
    )
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('two_pointers_made', sa.Integer(), nullable=False),
    sa.Column('two_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('three_pointers_made', sa.Integer(), nullable=False),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('total_rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Integer(), nullable=False),
    sa.Column('extra_stats', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game_stats')
    )
    op.create_table('team_game_stats',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('two_pointers_made', sa.Integer(), nullable=False),
    sa.Column('two_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('three_pointers_made', sa.Integer(), nullable=False),
    sa.Column('three_pointers_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('total_rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.Column('fast_break_points', sa.Integer(), nullable=False),
    sa.Column('points_in_paint', sa.Integer(), nullable=False),
    sa.Column('second_chance_points', sa.Integer(), nullable=False),
    sa.Column('bench_points', sa.Integer(), nullable=False),
    sa.Column('biggest_lead', sa.Integer(), nullable=False),
    sa.Column('time_leading', sa.Integer(), nullable=False),
    sa.Column('extra_stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'team_id')
    )
    op.create_table('play_by_play_event_links',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('related_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['play_by_play_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_event_id'], ['play_by_play_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'related_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert the migration.

    This function contains the operations to downgrade the database schema
    from this revision. It should exactly reverse the upgrade operations.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_by_play_event_links')
    op.drop_table('team_game_stats')
    op.drop_table('player_game_stats')
    op.drop_table('play_by_play_events')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_game_date')

    op.drop_table('games')
    # ### end Alembic commands ###
